### ISSUE TITLE
Is there a way to define in splitted config files custom task definitions too?

### ISSUE THREAD

**Issue by alberto-chiesa** [creynders/load-grunt-configs#19]
Or, can I define someway tasks that will be passed on subsequent registerTask(...) calls?

An example would be great.

Btw, thanks for this insanely useful plugin! My team reached the point in which the Gruntfile becomes difficult to manage (around 400 rows) and we found out the split-by-argument schema to work best for us.

Thank you!

**Comment by creynders** [comment]
AFAIK you can register them inside the `js` or `coffee` config files themselves, if you use a combination of the modular and multi-task approach, e.g.:

```js
//config/jshint.js
module.exports = function(grunt, options){
  grunt.registerTask('lint', ['jshint']);
  return {
    tasks: {
      jshint:{
        source:{
        	src: "src/*.js"        
        }
      } 
    }
  }
}
 ```
I don't have the time to test this out, but _I think_ this should work. It registers a task `lint` which will run all `jshint` targets, in this case a target called `source`.

**Comment by alberto-chiesa** [comment]
I'm going to test this out and report here if it works.
Thanks for the suggestion!

**Comment by alberto-chiesa** [comment]
I can now confirm your suggestion works flawlessly!

Thank you. This module makes the dreaded Grunt management a breeze!
