### ISSUE TITLE
add support for grunt 1.0.0

### ISSUE THREAD

**Issue by sagiegurari** [creynders/load-grunt-configs#25]
since the peer dependency is of >=0.4.0, new grunt version (1.x.x) is not supported.
Can you please update the needed?

**Comment by creynders** [comment]
@sagiegurari what do you think, should I just drop the peerDependency, or set it to "latest", or?

**Comment by creynders** [comment]
Ah found the answer on the grunt site:

>If you have a Grunt plugin that includes grunt in the peerDependencies section of your package.json, we recommend tagging with "grunt": ">=0.4.0"

⛄  dependency ranges are becoming totally fucking useless ...

**Comment by sagiegurari** [comment]
ya. problem.
but I do think you should first of all test your plugin with grunt 1.x.x because it is not fully backward compatible and your plugin might break due to their changes.

**Comment by sagiegurari** [comment]
thanks a lot :+1:

**Comment by creynders** [comment]
@sagiegurari I tested it out locally and everything seemed to work fine. But this was with a small grunt config and only a few grunt plugins. Could you check whether this works for your projects too? You can install it with `npm i load-grunt-configs@next'

**Comment by sagiegurari** [comment]
Sure, I'll try to check in few hours.
Problem is that few more plugins I use have same problem and I opened issues for them as well.
But I'll check. Thanks for the quick support

**Comment by sagiegurari** [comment]
Works great for me and I have complex split in my grunt build.
When can you publish it to npm?

**Comment by sagiegurari** [comment]
Can you please publish it to npm?
